### PR TITLE
Integration with Apache Toree 0.2.0-dev1 and Spark 2.1.0

### PR DESCRIPTION
**Pull request by ansotoPhd**

### CODE REVIEW

**Comment by ansotoPhd** [comment]
#243

**Comment by grahamwills** [comment]
Many thanks for the contribution; I have merged the changes into master along with several other contributions from the community. If you have a  moment to check that the merges all went well, that would be excellent. Thanks again!

**Comment by asorianostratio** [comment]
It's a pleasure to contribute! I have checked a build from master branch and everything seem to work fine (Toree kernel boots, loads the magic, all example notebooks run without problems with Spark 2.1.0 and all brunel graphs and charts are correctly displayed ). It looks good to me.

**Comment by grahamwills** [comment]
Excellent, thanks for verifying

**Pull request merged**
